database:
  host: "localhost"
  username: "root"
  password: "password"
  database: "occupation_db"
  port: 3306

excel:
  filepath: "test.xlsx"

ai:
  api_key_env: "DASHSCOPE_API_KEY"
  base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1/"
  model: "qwen-plus"
  temperature: 0.1
  enabled: true

logging:
  level: "info"